language: python
python:
  - 2.6
  - 2.7
install:
    - pip install coveralls --use-mirrors
    - pip install -r requirements.pip --use-mirrors
before_script:
  - psql -c 'create database skeleton;' -U postgres
script:
    - coverage run manage.py test
after_success:
    - coveralls
